apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite
  namespace: mysite
  labels:
    app: mysite
    version: main
spec:
  selector:
    matchLabels:
      app: mysite
      version: main
  template:
    metadata:
      labels:
        app: mysite
        version: main
    spec:
      containers:
      - name: webstore
        image: bagas25/mysite:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
